stages:
  - build
cache:
  paths:
  - vendor
build:
  stage: build
  tags:
    - docker
  image: simpproject/centos:7-ruby24
  artifacts:
    paths:
      - 'doc'
  script:
          - sudo yum install -y libjpeg-devel zlib-devel python-devel
          - sudo yum install -y python2-pip
          - sudo pip install -q -r requirements.txt
          - bundle install --path=/cache
          - bundle update
          - bundle exec rake docs:html

